# Generated by Django 4.1.7 on 2023-03-19 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irp_assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='beschrijving',
            new_name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='irp_assessment.assessment'),
        ),
    ]
