# Generated by Django 4.1.7 on 2023-03-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irp_assessment', '0003_item_category_item_deliverable_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='firstq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
