# Generated by Django 4.1.7 on 2023-03-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irp_assessment', '0004_assessment_firstq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='firstq',
        ),
    ]
