# Generated by Django 4.1.7 on 2023-04-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irp_assessment', '0005_remove_assessment_firstq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='irp_assessment.assessment'),
        ),
    ]
