# Generated by Django 4.1.7 on 2023-04-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irp_assessment', '0006_alter_item_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='maturity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='proof',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='summary',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
