# Generated by Django 4.1.7 on 2023-04-08 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
        ('irp_assessment', '0007_item_maturity_item_proof_item_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deliverable_description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_nr',
        ),
        migrations.RemoveField(
            model_name='item',
            name='respondent',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stage',
        ),
        migrations.AddField(
            model_name='item',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='frameworks.frameitem'),
        ),
    ]
