# Generated by Django 4.1.7 on 2023-04-10 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0002_framelevel'),
        ('irp_assessment', '0008_remove_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='frameworks.framework'),
        ),
    ]
