# Generated by Django 4.1.7 on 2023-04-10 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frameworks', '0002_framelevel'),
        ('irp_assessment', '0010_alter_assessment_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='frameworks.framework'),
        ),
    ]
