# Generated by Django 4.1.7 on 2023-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irp_assessment', '0011_alter_assessment_creator_alter_assessment_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stage',
            field=models.CharField(default='design', max_length=100),
        ),
    ]
