# Generated by Django 4.1.7 on 2023-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irp_assessment', '0012_item_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
