# Generated by Django 4.1.7 on 2023-05-17 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esb', '0001_initial'),
        ('projects', '0002_project_sds'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='esc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='esb.esc'),
        ),
    ]
