# Generated by Django 4.1.7 on 2023-03-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='team_members',
            new_name='members',
        ),
    ]
