# Generated by Django 4.1.7 on 2023-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_team_members_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
