# Generated by Django 4.1.7 on 2023-03-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_enddate_alter_project_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateTimeField(),
        ),
    ]
