# Generated by Django 4.1.7 on 2023-03-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_enddate_alter_project_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
