# Generated by Django 4.1.7 on 2023-04-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='frameworks.frameitem')),
            ],
        ),
    ]
