# Generated by Django 4.1.7 on 2023-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0002_framelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameitem',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
