# Generated by Django 4.1.7 on 2023-04-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sds', '0002_sds_sdsquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sds',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='sds',
            name='name',
        ),
    ]
